name: Spesa
description: Spesa lista.

version: 1.2.4+5

environment:
  sdk: ">=2.6.0 <3.0.0"
  #sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  spesa_repository:
    path: spesa_repository
  rxdart: ^0.23.1
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.1+11
  http: 0.12.0+1
  photo_view: ^0.9.2
  package_info: ^0.4.0+6
  url_launcher: 5.0.0
  flutter_svg: 0.17.4
  flutter_image_compress: ^0.6.7
  firebase_auth: ^0.16.0
  firebase_storage:
  google_sign_in: ^4.1.1
  equatable: ^1.0.1
  flutter_bloc: ^4.0.0
  meta: ^1.1.8
  font_awesome_flutter: ^8.4.0
  firebase_image: ^0.1.6
  ########https://pub:dev/packages/firebase_image#-installing-tab-:
  random_string: ^2.0.1
  flutter_touch_spin: ^1.0.1
  firebase_ml_vision: ^0.9.3+8
  permission_handler: ^4.4.0+hotfix.2
  #clipboard_manager: ^0.0.4
  exif: ^1.0.2
  flutter_exif_rotation: ^0.2.7
  badges: ^1.1.1
  dotted_border: ^1.0.5
  shared_preferences: ^0.5.6+3
  intro_views_flutter: ^2.8.1

  ###firebase_core: ^0.4.3+3
  #spesa_repository:
  #  path: spesa_repository



dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/no_content.svg
    - assets/loading.svg
    - assets/launcher_icon.png
    - assets/images/Screenshot_1.png
    - assets/images/Screenshot_2.png
    - assets/images/Screenshot_3.png
    - assets/images/Screenshot_4.png
    - assets/fonts/



module:
    androidX: true



